### ISSUE TITLE
bout installing edge impulse cli

### ISSUE THREAD

**Issue by Chunchun-tian** [edgeimpulse/edge-impulse-cli#13]
When I use note.js (v14.17.0.) to install cli, and then run "dge-impulse-daemon", the following error will appear. What do I need to do?

![image](https://user-images.githubusercontent.com/56999025/121179237-0fc0b500-c892-11eb-8b6b-c3f19bf80a25.png)

**Comment by alwint3r** [comment]
Had the same problem when conducting workshops for non-nodejs developers. Some failed to compile the serialport bindings even when they have visual studio tools installed.

However, I may have found a workaround for windows users and here's what I did:

1. Clone this repository
2. Edit package.json, and change the version of serialport to "9.2.4", exactly that version.
3. Run `npm install` on the edge-impulse-cli directory
4. Run `npx tsc -p .` to build the CLIs. Note that there's an npm build script, but most of my workshop participant encountered error when running the build script, so that's the alternative.
5. Then run `npm install -g .` to install edge-impulse-cli

So far I haven't found any problems after doing this. Use it on your own risk.

**Comment by ijdoc** [comment]
@alwint3r the build command failure in Windows is likely due to npm using CMD instead of powershell as the default shell. This can be updated with:
```
npm config set script-shell pwsh [--global]
```
